In [ ]:
## Mini-Projeto Análise de Vendas

In [1]:
import pandas as pd

vendas = [
    {"produto": "Notebook", "categoria": "Eletrônicos", "valor": 3500, "cliente": "Lucas"},
    {"produto": "Mouse", "categoria": "Eletrônicos", "valor": 150, "cliente": "Pedro"},
    {"produto": "Teclado", "categoria": "Eletrônicos", "valor": 300, "cliente": "Ana"},
    {"produto": "Cadeira Gamer", "categoria": "Móveis", "valor": 1200, "cliente": "Lucas"},
    {"produto": "Monitor", "categoria": "Eletrônicos", "valor": 900, "cliente": "Marcelo"},
    {"produto": "Mesa Escritório", "categoria": "Móveis", "valor": 700, "cliente": "Pedro"},
    {"produto": "Headset", "categoria": "Eletrônicos", "valor": 400, "cliente": "Ana"},
    {"produto": "Notebook", "categoria": "Eletrônicos", "valor": 4200, "cliente": "Marcelo"}
]

df = pd.DataFrame(vendas)

df

           produto    categoria  valor  cliente
0         Notebook  Eletrônicos   3500    Lucas
1            Mouse  Eletrônicos    150    Pedro
2          Teclado  Eletrônicos    300      Ana
3    Cadeira Gamer       Móveis   1200    Lucas
4          Monitor  Eletrônicos    900  Marcelo
5  Mesa Escritório       Móveis    700    Pedro
6          Headset  Eletrônicos    400      Ana
7         Notebook  Eletrônicos   4200  Marcelo

In [2]:
df["valor"].mean()

1418.75

In [4]:
df["tipo_venda"] = "Normal"

df.loc[df["valor"] >= 2000, "tipo_venda"] = "Alta"

df

           produto    categoria  valor  cliente tipo_venda
0         Notebook  Eletrônicos   3500    Lucas       Alta
1            Mouse  Eletrônicos    150    Pedro     Normal
2          Teclado  Eletrônicos    300      Ana     Normal
3    Cadeira Gamer       Móveis   1200    Lucas     Normal
4          Monitor  Eletrônicos    900  Marcelo     Normal
5  Mesa Escritório       Móveis    700    Pedro     Normal
6          Headset  Eletrônicos    400      Ana     Normal
7         Notebook  Eletrônicos   4200  Marcelo       Alta

In [5]:
df["tipo_venda"].value_counts()

tipo_venda
Normal    6
Alta      2
Name: count, dtype: int64

In [6]:
df["tipo_venda"].value_counts(normalize=True) * 100

tipo_venda
Normal    75.0
Alta      25.0
Name: proportion, dtype: float64

In [7]:
vendas_altas = df[df["tipo_venda"] == "Alta"]

vendas_altas

    produto    categoria  valor  cliente tipo_venda
0  Notebook  Eletrônicos   3500    Lucas       Alta
7  Notebook  Eletrônicos   4200  Marcelo       Alta